# Color palette generation configuration
palette_sizes:
  - 8
  - 16
  - 32
  - 64

# Superpixels creation configuration
num_superpixels:
  - 20
  - 50
  - 100

original_image_directory: "original_images"
image_directory: "resized_images"
test_image_directory: "test_images"
output_directory: "data"

# Number of worker processes to use
# If not specified, it will use the number of CPU cores
num_workers: 4

# Target size for resizing images (width, height)
target_size: [640, 480]